### ISSUE TITLE
Homework Mode + To-do list

### ISSUE THREAD

**Issue by bluecandle** [ywj7373/MC-group2#1]
**Homework Mode**

- [x] Block all apps selected in settings

- [x] Send notification with check-in prompt
- [x] Check in through app or notification
- [x] Permission to use motion data?
- [x] Check in through movement (e.g. shaking, flipping phone)
- [x] Investigate how to use gestures through movement
- [x] Permission to use alarm?
- [x] Activate alarm on no check in
- [x] Turn on homework mode
- [x] Turn off homework mode
- [x] Block turn off if tasks due soon that have not been completed? (could be very annoying if - - you actually cannot do more homework at that time, but will do it later)
- [x] Input from user “I have done my homework”

**Configure homework mode**

- [x] Select apps to be blocked on activation of HW mode
- [x] Select interval of check-in time
- [x] Button to turn on/turn off

**To-do list** ( not things to do! name of the feature)
- [x] can create task
- [x] can delete task
- [x] task can contain memo
- [x] task can contain Date and time
