### ISSUE TITLE
Usage Tracking + App blocking

### ISSUE THREAD

**Issue by ywj7373** [ywj7373/MC-group2#2]
### Main features
- Track usage of restricted apps
- Block app temporarily for set duration
- Require time passed + step count to unblock
- Reset timer after taking a break for set duration
- Option to automatically enable and disable feature based on items on todo list 

### Tasks (responsible: Rachel + Marita)
- [x] Get permission to see usage data for app, ActivityManager #5
- [x] Read usage data #6 
- [x] Implement blocking app MVP #7
- [x] Block app after using it for set restriction #8 
- [x] Send notification when used app for set duration #9 
- [x] Add setting for maximum time limit for app (default 40 min) #10
- [x] Send notification 5 min before block warning that if you use if for longer it will get blocked #11
- [x] Get app list (so that you can select them to block) #12
- [x] Add input for selecting apps to restrict #13
- [x] Reset app block countdown if user stops using app for set duration #14
- [x] Add setting for block duration (default 10 min) #15
- [x] Send user to blocked app screen after blocking app #16
- [x] Create blocked app screen (should show break countdown), investigate difficulty of creating popup-modal for this #17
- [x] Add walking requirement to unlock app #18
- [x] Show step count and requirement on blocked app screen #19
- [x] Get permission to use pedometer #20
- [x] Read step count #21
- [x] Add setting for step count required for unblocking app (default 50 steps) #22
- [x] Add setting for enabling or disabling walking requirement (default ON) #23
- [x] Investigate what data we can get from the phone through ActivityManager to use for smart sensing of procrastinating #24
- [x] Develop a smarter algorithm for detecting procrastinating (smarter than static 40 min limit) #25 

#### End goal: 
- Create to-do list to enable activation of this mode only on specific times (so it does not turn on when you actually have nothing you need to do and can spend as much time on your phone as you want).

#### Specific tasks:
- [x] Add database for storing data
- [x] Create input method for adding task (description, due date, etc..)
- [x] Show tasks on todo list
- [x] Add setting to for when to activate of this feature (always on, only when stuff due on todo list)
