### ISSUE TITLE
Location Alert + Score System

### ISSUE THREAD

**Issue by ywj7373** [ywj7373/MC-group2#3]
## Assigned Members
Young Woong Jun, Seung Woo Jo

# 1st Iteration
- [x] Look for Google Maps Directions API or Kakao Map API or Naver API  (Naver or Kakao is preferred)

# 2nd Iteration
- [x] Reading GPS data  
- [x] Getting permission to use GPS  
- [x] User can search location through Naver API
- [x] Compare current device location with planned location (Are you at the right place?) (Is current coordinates within the accepted coordinate range? (broadened acceptance area)   
- [x] Estimating travel time (what algorithm would you use?)
- [ ] Activate GPS 1 hour before scheduled location reminder  
- [x] Check every 10 minutes for location and estimate travel time  
- [ ] Use that estimate to decide when to send out reminder  
- [ ] Check where you are 40 min before class and see if travel time is long 

# 3rd Iteration
- [ ] Send notification in advance of time you are supposed to be at location  
- [ ] Send notification at set time you should be at location (“You made it! [score +1]” or “You missed ~~~,”
(Note: No reason to go if you already missed it? Could feel meaningless to some. Maybe something ala eAttendance, Present (interval of time accepted), Late-in (can still get reward for still getting there), Absent)
If missed time exactly, notification says “Hurry up! You can still make it! 10 min left to get full score (1p)”
If you make it in time then, new notification “You made it! Score +1. Estimated grade A” 
- [x] Investigate battery saving policies  
- [x] Implement some form of power conservation for GPS  

# 4th Iteration
- [ ] Keep score count (Decide scoring system/gamification)
- [ ] Cumulative kind of grading estimating  
- [ ] Display current score (grade)  
- [ ] Could add different statistics (nice to have, not prioritised if time consuming)  
- [ ] List of location reminders set up  
- [ ] Make a timetable(with location) functionality (advanced level, nice to have but high complexity)  

# 5th Iteration
- [ ] Test if the notification is sent
- [ ] Test if the scoring system is working
- [ ] Test if the app is tracking your location
