### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by bluecandle** [ywj7373/MC-group2#54]
- [x] Implement Notification Example
- [x] Send Notification when location-reminder situation
- [x] Send Notification when homework mode situation

**Comment by bluecandle** [comment]
Implemented the basic notification example (feat/54)

**Comment by bluecandle** [comment]
Well done.
